<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>search</name>
  <version>0.0.1</version>
  <description>Search custom flight mode for PX4 with a persistent SearchPlanner working plan.</description>
  <maintainer email="pordipatrik@gmail.com">patrik_ark</maintainer>
  <license>CC-BY-SA-4.0</license>

  <buildtool_depend>eigen3_cmake_module</buildtool_depend>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>pkg-config</build_depend>
  <build_depend>libmosquitto-dev</build_depend>
  <exec_depend>libmosquitto1</exec_depend>
  <buildtool_export_depend>eigen3_cmake_module</buildtool_export_depend>

  <depend>ament_index_cpp</depend>
  <depend>eigen</depend>
  <depend>rclcpp</depend>
  <depend>px4_msgs</depend>
  <depend>px4_ros2_cpp</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
